PROJECT(VulkanTutorial)
FIND_PACKAGE(Vulkan REQUIRED)

#add_subdirectory(00_vk_env)
#add_subdirectory(00_base)

add_subdirectory(01_VkInstance)
add_subdirectory(03_physicalDevice)
add_subdirectory(04_logicDevice)
add_subdirectory(05_windowSurface)
add_subdirectory(06_swapchain)
add_subdirectory(07_imageView)
add_subdirectory(GraphicsPipeline)
add_subdirectory(12_Framebuffers)
add_subdirectory(13_CommandBuffers)
add_subdirectory(14_Rendering)
add_subdirectory(15_FramesInFlight)
add_subdirectory(16_SwapChainRecreation)
add_subdirectory(VertexBuffer)
add_subdirectory(UniformBuffer)
