CMAKE_MINIMUM_REQUIRED(VERSION 3.15)
PROJECT(VulkanTriangle LANGUAGES C CXX)

SET(CMAKE_CXX_STANDARD 17)

FIND_PACKAGE(glm CONFIG REQUIRED)
FIND_PACKAGE(Vulkan REQUIRED)

ADD_COMPILE_OPTIONS("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
ADD_COMPILE_OPTIONS("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")

ADD_SUBDIRECTORY(example)
ADD_SUBDIRECTORY(src)
