SET(target_ c13_texture)

# run glslangValidator build shader
FIND_PROGRAM(GLSLANG_VALIDATOR glslangValidator)
FILE(GLOB SHADER_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/shaders/*.glsl)

FOREACH(SHADER ${SHADER_SOURCES})
    # get file name
    GET_FILENAME_COMPONENT(SHADER_NAME ${SHADER} NAME_WE)

    # get file extension name
    GET_FILENAME_COMPONENT(SHADER_EXT ${SHADER} EXT)
    STRING(REGEX MATCH "frag|vert|comp" STAGE ${SHADER_NAME})
    SET(OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/shaders/${SHADER_NAME}.spv")

    ADD_CUSTOM_COMMAND(
        OUTPUT ${OUTPUT_FILE}
        COMMAND ${GLSLANG_VALIDATOR} -V ${SHADER} -S ${STAGE} -o ${OUTPUT_FILE}
        DEPENDS ${SHADER}
        COMMENT "Compiling ${SHADER} to SPIR-V"
        VERBATIM
    )
    LIST(APPEND SHADER_SPV_FILES ${OUTPUT_FILE})
    MESSAGE(STATUS "${SHADER_NAME} -- ${STAGE} -- ${SHADER_EXT}")
ENDFOREACH()

SET(custom_target "${target_}_CompileShaders")

ADD_CUSTOM_TARGET(${custom_target} ALL DEPENDS ${SHADER_SPV_FILES})

FILE(GLOB SOURCES_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/*.h
        ${CMAKE_CURRENT_SOURCE_DIR}/*.hpp
)

ADD_EXECUTABLE(${target_} ${SOURCES_FILES})
ADD_DEPENDENCIES(${target_} ${custom_target})

FIND_PACKAGE(glm CONFIG REQUIRED)
FIND_PACKAGE(Stb REQUIRED)

if(NOT Stb_INCLUDE_DIR)
    set(Stb_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
endif()

TARGET_INCLUDE_DIRECTORIES(${target_} PRIVATE
    ${Vulkan_INCLUDE_DIR}
    ${Stb_INCLUDE_DIR}
)

TARGET_LINK_LIBRARIES(${target_} PRIVATE
    ${Vulkan_LIBRARY}
    glfw
 )

# copy files
FILE(COPY ${CMAKE_CURRENT_SOURCE_DIR}/sources DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/)
