PROJECT(VulkanClass)
FIND_PACKAGE(Vulkan REQUIRED)

# ADD_SUBDIRECTORY(c06_renderloop_new)

ADD_SUBDIRECTORY(c00_framework)
ADD_SUBDIRECTORY(c01_instance)
ADD_SUBDIRECTORY(c02_devices)
ADD_SUBDIRECTORY(c03_surface)
ADD_SUBDIRECTORY(c04_swapchain)
ADD_SUBDIRECTORY(c05_renderloop)
ADD_SUBDIRECTORY(c06_submitting)
ADD_SUBDIRECTORY(c07_renderpass)
ADD_SUBDIRECTORY(c08_recreating)
ADD_SUBDIRECTORY(c09_renderPipeline)
ADD_SUBDIRECTORY(c10_vertices)
ADD_SUBDIRECTORY(c11_indices)
ADD_SUBDIRECTORY(c12_uniform_buffer)
add_subdirectory(c13_texture)
add_subdirectory(c14_animation)

