site_name: VulkanLearn 文档
site_url: https://example.com
theme:
    name: material
    language: zh
nav:
    - 首页: index.md
    - Vulkan 入门:
        - Vulkan简介: 0.Vulkan/vulkan_intro.md
        - 初始化: 1.Instance/Init.md
        - 渲染循环: render_loop.md
    - 调试与性能:
        - Validation Layers: validation.md
        - 性能优化: performance.md
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
